# Generated by Django 4.1 on 2022-10-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
    ]
